// Generated by https://quicktype.io

export interface FetchAllStudentResponse {
  message: string;
  body:    Estudiante[];
}

export interface FetchAllStudentResponseDetail {
  message: string;
  body:    Estudiante;
}

export interface Estudiante {
  _id:       string;
  cedula:    string;
  apellidos: string;
  nombres:   string;
  semestre:  string;
  carrera:   string;
  facultad:  string;
}
